import http from 'node:http';
import fs from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
import { chromium } from 'playwright';
const root=process.cwd(),types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8'};
const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,'http://127.0.0.1'),rel=u.pathname==='/'?'/index.html':u.pathname,file=path.join(root,rel.replace(/^\/+/,'')),data=await fs.readFile(file);res.writeHead(200,{'content-type':types[path.extname(file)]||'application/octet-stream','cache-control':'no-store'});res.end(data)}catch{res.writeHead(404);res.end('not found')}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const port=server.address().port,browser=await chromium.launch({headless:true});
async function pageWithFake({validOnline=false}={}){const page=await browser.newPage({viewport:{width:1280,height:800}});await page.addInitScript(({validOnline})=>{const listeners=new WeakMap();const emit=(ws,t,e={})=>{for(const f of listeners.get(ws)?.get(t)||[])f.call(ws,e);const h=ws['on'+t];if(typeof h==='function')h.call(ws,e)};class W{static OPEN=1;constructor(){this.readyState=0;listeners.set(this,new Map());setTimeout(()=>{this.readyState=1;emit(this,'open');emit(this,'message',{data:JSON.stringify({type:'hello',protocol:1,service:'qqnd-game-server'})})},0)}addEventListener(t,f){const m=listeners.get(this),a=m.get(t)||[];a.push(f);m.set(t,a)}removeEventListener(){}send(raw){const m=JSON.parse(raw);window.__frames=(window.__frames||[]).concat(m);if(m.type==='session.resume'){setTimeout(()=>{if(validOnline)emit(this,'message',{data:JSON.stringify({type:'session.resumed',session:{id:m.sessionId,nickname:'Tester',connected:true},rooms:[{id:'TEST-ROOM',game:'duren',name:'Resume',visibility:'private',source:'manual',status:'in_game',ownerSessionId:m.sessionId,minPlayers:2,maxPlayers:3,players:[{id:m.sessionId,nickname:'Tester',connected:true},{id:'guest',nickname:'Alice',connected:true}]}]})});else emit(this,'message',{data:JSON.stringify({type:'error',code:'invalid_session_credentials',message:'invalid_session_credentials'})})},0)}if(m.type==='game.state.get'&&validOnline){const s=structuredClone(window.Durak.game.state);s.players=[{name:'Tester',isBot:false,difficulty:'normal'},{name:'Alice',isBot:false,difficulty:'normal'}];s.hands=[[],[]];s.deck=[];s.out=[false,false];s.bubbles=[null,null];s.round=3;s.phase='attack';s.attacker=0;s.defender=1;setTimeout(()=>emit(this,'message',{data:JSON.stringify({type:'game.state',roomId:'TEST-ROOM',revision:9,botSeats:[],hostSessionId:m.sessionId||'',authoritative:false,viewerSeat:0,presence:[],state:s})}),0)}}close(){this.readyState=3;emit(this,'close',{code:1000})}}window.WebSocket=W;window.__validOnline=validOnline},{validOnline});await page.goto(`http://127.0.0.1:${port}/`,{waitUntil:'load'});await page.waitForFunction(()=>window.Durak?.game?.state&&window.DurakMultiplayer);return page}
try{
  const offline=await pageWithFake();await offline.click('[data-action="menu-new-game"]');await offline.click('[data-action="confirm-new-game"]');await offline.waitForFunction(()=>window.Durak.game.state.round>=1);const before=await offline.evaluate(()=>({round:Durak.game.state.round,phase:Durak.game.state.phase,hand:Durak.game.state.hands[0].map(c=>c.id)}));await offline.reload({waitUntil:'load'});await offline.waitForFunction(()=>window.DurakMultiplayer);assert.equal(await offline.locator('#menu-continue').isVisible(),true);await offline.click('#menu-continue');const after=await offline.evaluate(()=>({round:Durak.game.state.round,phase:Durak.game.state.phase,hand:Durak.game.state.hands[0].map(c=>c.id)}));assert.deepEqual(after,before,'offline autosave was not restored');await offline.close();
  const online=await pageWithFake({validOnline:true});await online.evaluate(()=>{localStorage.setItem('durniowie-session-v1',JSON.stringify({round:2,players:[{name:'Offline',isBot:false}],hands:[[]],deck:[],trump:'H',trumpCard:null,discard:[],discardCount:0,table:[],attacker:0,defender:0,phase:'attack',taking:false,passed:[],thrower:null,defenseTarget:0,boutDefenderStart:0,maxAttacks:6,out:[false],outOrder:[],log:[],status:null,rules:{throwInAll:true,transfer:false,limitSix:true},botConfig:[],botCount:0,stats:{wins:0,losses:0,draws:0}}));localStorage.setItem('duren.qqnd.server-session.v1',JSON.stringify({sessionId:'host',resumeToken:'r'.repeat(64),nickname:'Tester',roomId:'TEST-ROOM',onlineEligible:true}));Durak.game.showMainMenu();Durak.game.refreshMainMenu()});assert.equal(await online.locator('#menu-continue').getAttribute('data-resume-type'),'online');await online.click('#menu-continue');await online.waitForFunction(()=>window.DurakMultiplayer.debug.state.inGame===true);assert.equal(await online.evaluate(()=>Durak.game.state.round),3,'online resume did not win priority');await online.close();
  const fallback=await pageWithFake({validOnline:false});await fallback.evaluate(()=>{localStorage.setItem('durniowie-session-v1',JSON.stringify({round:4,players:[{name:'Offline',isBot:false}],hands:[[]],deck:[],trump:'H',trumpCard:null,discard:[],discardCount:0,table:[],attacker:0,defender:0,phase:'attack',taking:false,passed:[],thrower:null,defenseTarget:0,boutDefenderStart:0,maxAttacks:6,out:[false],outOrder:[],log:[],status:null,rules:{throwInAll:true,transfer:false,limitSix:true},botConfig:[],botCount:0,stats:{wins:0,losses:0,draws:0}}));localStorage.setItem('duren.qqnd.server-session.v1',JSON.stringify({sessionId:'bad',resumeToken:'r'.repeat(64),nickname:'Tester',roomId:'OLD-ROOM',onlineEligible:true}));Durak.game.showMainMenu();Durak.game.refreshMainMenu()});await fallback.click('#menu-continue');await fallback.waitForFunction(()=>document.querySelector('#menu-continue')?.dataset.resumeType==='offline');await fallback.click('#menu-continue');assert.equal(await fallback.evaluate(()=>Durak.game.state.round),4,'stale online resume destroyed offline fallback');await fallback.close();
  console.log('Resume priority smoke: PASS');
}finally{await browser.close();await new Promise(r=>server.close(r))}
