(() => {
  'use strict';
  const D = window.DurakMP = {};
  D.frame = document.getElementById('durak-game');
  D.$ = (id) => document.getElementById(id);
  D.MAX_MESSAGE = 64 * 1024;
  D.ROOM_RE = /^[A-HJ-NP-Z2-9]{4}-[A-HJ-NP-Z2-9]{4}$/;
  D.ICE_SERVERS = window.DURAK_ICE_SERVERS || [
    { urls:'stun:stun.cloudflare.com:3478' },
    { urls:'stun:stun.l.google.com:19302' },
  ];
  D.TEXT = {
    pl:{online:'Gra online',privateTable:'PRYWATNY STÓŁ P2P',title:'Multiplayer',lead:'Utwórz prywatny pokój albo dołącz kodem. Po zestawieniu połączenia rozgrywka idzie bezpośrednio między przeglądarkami.',name:'Nazwa gracza',create:'Utwórz pokój',join:'Dołącz',networkNote:'Tryb online wymaga HTTPS i aktywnej usługi sygnalizacyjnej pod /api/. Gra offline działa bez niej.',roomCode:'Kod pokoju',copy:'Kopiuj',copied:'Skopiowano',fillBot:'Uzupełnij trzecie miejsce botem',fillBotHint:'Bot działa wyłącznie u hosta i nie ma własnego połączenia sieciowego.',difficulty:'Poziom bota',leave:'Opuść',start:'Rozpocznij grę',host:'Host',human:'Gracz',bot:'Bot',empty:'Wolne miejsce',connected:'Połączony',ready:'Gotowy',reserved:'Zarezerwowane',creating:'Tworzę pokój…',joining:'Łączenie z pokojem…',signalingError:'Nie udało się połączyć z usługą sygnalizacyjną.',invalidName:'Nazwa musi mieć 3–20 znaków.',invalidRoom:'Wpisz poprawny kod pokoju.',waiting:'Czekam na co najmniej jednego drugiego gracza.',canStart:'Stół gotowy. Host może rozpocząć.',guestWait:'Połączono. Czekaj, aż host rozpocznie grę.',roomFull:'Pokój jest pełny albo miejsce jest zarezerwowane dla bota.',connectionLost:'Połączenie zostało przerwane',connectionLostText:'Rozgrywka została zatrzymana, aby nie dopuścić do rozjazdu stanu.',backMenu:'Wróć do menu',illegal:'Host odrzucił nielegalny ruch.',unavailableLocal:'Multiplayer nie działa z adresu file://. Uruchom grę przez HTTPS; tryb offline nadal działa normalnie.',webRtcFailed:'Nie udało się zestawić połączenia WebRTC.',hostGone:'Host rozłączył się.',guestGone:'Gracz rozłączył się.',botSeat:'Bot · {level}',thirdOptional:'Trzecie miejsce jest opcjonalne.'},
    en:{online:'Online game',privateTable:'PRIVATE P2P TABLE',title:'Multiplayer',lead:'Create a private room or join with a code. Once connected, gameplay travels directly between browsers.',name:'Player name',create:'Create room',join:'Join',networkNote:'Online mode needs HTTPS and the signaling service at /api/. Offline play does not depend on it.',roomCode:'Room code',copy:'Copy',copied:'Copied',fillBot:'Fill the third seat with a bot',fillBotHint:'The bot runs only on the host and has no network connection of its own.',difficulty:'Bot difficulty',leave:'Leave',start:'Start game',host:'Host',human:'Player',bot:'Bot',empty:'Empty seat',connected:'Connected',ready:'Ready',reserved:'Reserved',creating:'Creating room…',joining:'Joining room…',signalingError:'Could not reach the signaling service.',invalidName:'Name must be 3–20 characters.',invalidRoom:'Enter a valid room code.',waiting:'Waiting for at least one other human player.',canStart:'Table ready. The host can start.',guestWait:'Connected. Waiting for the host to start.',roomFull:'The room is full or the seat is reserved for a bot.',connectionLost:'Connection lost',connectionLostText:'The game was stopped to prevent the state from diverging.',backMenu:'Back to menu',illegal:'The host rejected an illegal move.',unavailableLocal:'Multiplayer cannot run from file://. Serve the game over HTTPS; offline play still works normally.',webRtcFailed:'Could not establish the WebRTC connection.',hostGone:'The host disconnected.',guestGone:'A player disconnected.',botSeat:'Bot · {level}',thirdOptional:'The third seat is optional.'},
    de:{online:'Online spielen',privateTable:'PRIVATER P2P-TISCH',title:'Mehrspieler',lead:'Erstelle einen privaten Raum oder tritt mit einem Code bei. Danach läuft das Spiel direkt zwischen den Browsern.',name:'Spielername',create:'Raum erstellen',join:'Beitreten',networkNote:'Online benötigt HTTPS und den Signalisierungsdienst unter /api/. Offline bleibt unabhängig.',roomCode:'Raumcode',copy:'Kopieren',copied:'Kopiert',fillBot:'Dritten Platz mit Bot füllen',fillBotHint:'Der Bot läuft ausschließlich beim Host.',difficulty:'Bot-Stärke',leave:'Verlassen',start:'Spiel starten',host:'Host',human:'Spieler',bot:'Bot',empty:'Freier Platz',connected:'Verbunden',ready:'Bereit',reserved:'Reserviert',creating:'Raum wird erstellt…',joining:'Verbindung…',signalingError:'Signalisierungsdienst nicht erreichbar.',invalidName:'Name: 3–20 Zeichen.',invalidRoom:'Gültigen Raumcode eingeben.',waiting:'Warte auf mindestens einen weiteren Menschen.',canStart:'Tisch bereit. Der Host kann starten.',guestWait:'Verbunden. Warte auf den Host.',roomFull:'Raum voll oder Platz für Bot reserviert.',connectionLost:'Verbindung unterbrochen',connectionLostText:'Das Spiel wurde gestoppt, damit der Zustand synchron bleibt.',backMenu:'Zum Menü',illegal:'Der Host hat einen ungültigen Zug abgelehnt.',unavailableLocal:'Mehrspieler funktioniert nicht über file://. Nutze HTTPS; Offline bleibt verfügbar.',webRtcFailed:'WebRTC-Verbindung fehlgeschlagen.',hostGone:'Der Host hat die Verbindung getrennt.',guestGone:'Ein Spieler hat die Verbindung getrennt.',botSeat:'Bot · {level}',thirdOptional:'Der dritte Platz ist optional.'},
    ru:{online:'Игра онлайн',privateTable:'ПРИВАТНЫЙ P2P-СТОЛ',title:'Мультиплеер',lead:'Создай приватную комнату или войди по коду. После соединения игра идёт напрямую между браузерами.',name:'Имя игрока',create:'Создать комнату',join:'Войти',networkNote:'Онлайн требует HTTPS и сервиса сигналинга на /api/. Офлайн от него не зависит.',roomCode:'Код комнаты',copy:'Копировать',copied:'Скопировано',fillBot:'Заполнить третье место ботом',fillBotHint:'Бот работает только у хоста.',difficulty:'Сложность бота',leave:'Выйти',start:'Начать игру',host:'Хост',human:'Игрок',bot:'Бот',empty:'Свободно',connected:'Подключён',ready:'Готов',reserved:'Занято',creating:'Создаю комнату…',joining:'Подключение…',signalingError:'Сервис сигналинга недоступен.',invalidName:'Имя должно быть длиной 3–20 символов.',invalidRoom:'Введите правильный код комнаты.',waiting:'Жду хотя бы одного второго игрока.',canStart:'Стол готов. Хост может начать.',guestWait:'Подключено. Ждите запуска хостом.',roomFull:'Комната заполнена или место зарезервировано для бота.',connectionLost:'Соединение потеряно',connectionLostText:'Игра остановлена, чтобы состояние не разошлось.',backMenu:'В меню',illegal:'Хост отклонил недопустимый ход.',unavailableLocal:'Мультиплеер не работает через file://. Откройте игру по HTTPS; офлайн работает как обычно.',webRtcFailed:'Не удалось установить WebRTC-соединение.',hostGone:'Хост отключился.',guestGone:'Игрок отключился.',botSeat:'Бот · {level}',thirdOptional:'Третье место необязательно.'},
  };
  D.mp = {active:false,role:null,roomCode:'',name:'Gracz',localSeat:0,hostToken:'',socket:null,peers:new Map(),peer:null,inGame:false,paused:false,botSeat:null,botDifficulty:'normal',revision:0,lastRevision:0,guestView:null,guestUi:{defenseTarget:0,transferMode:false},remoteQueue:new Map(),hooksInstalled:false,originalBot:null,originalRender:null,frameWindow:null,game:null,closeExpected:false,fakeTestMode:false};

  D.language = () => { try { const v=D.mp.frameWindow?.Durak?.game?.state?.settings?.language || D.mp.frameWindow?.Durak?.i18n?.language; return D.TEXT[v]?v:'pl'; } catch { return 'pl'; } };
  D.tr = (key,vars) => { let v=(D.TEXT[D.language()]||D.TEXT.pl)[key]||D.TEXT.pl[key]||key; if(vars)v=v.replace(/\{(\w+)\}/g,(_,k)=>vars[k]??`{${k}}`); return v; };
  D.applyLanguage = () => { document.documentElement.lang=D.language(); document.querySelectorAll('[data-mp-i18n]').forEach(n=>{const v=D.tr(n.dataset.mpI18n);if(v)n.textContent=v;}); };
  D.initials = (name) => Array.from(String(name||'?').trim()).slice(0,2).join('').toUpperCase();
  D.validName = (value) => { const n=String(value||'').normalize('NFKC').replace(/\s+/g,' ').trim(); const len=Array.from(n).length; return len>=3&&len<=20&&/^[\p{L}\p{N} _-]+$/u.test(n); };
  D.normalizeRoom = (value) => { const raw=String(value||'').toUpperCase().replace(/[^A-Z2-9]/g,''); return raw.length===8?`${raw.slice(0,4)}-${raw.slice(4)}`:''; };
  D.setStatus = (id,text,error=false) => { const n=D.$(id); if(!n)return; n.textContent=text||''; n.classList.toggle('error',!!error); };
  D.safeSend = (channel,message) => { try { if(channel?.readyState==='open') channel.send(JSON.stringify(message)); } catch {} };
  D.parseMessage = (raw) => { if(typeof raw!=='string'||raw.length>D.MAX_MESSAGE)return null; try { const x=JSON.parse(raw); return x&&typeof x.type==='string'?x:null; } catch { return null; } };
  D.wsUrl = (room) => `${location.protocol==='https:'?'wss:':'ws:'}//${location.host}/api/rooms/${encodeURIComponent(room)}/socket`;
  D.waitIceComplete = (pc,timeout=4500) => pc.iceGatheringState==='complete'?Promise.resolve():new Promise(resolve=>{let done=false;const finish=()=>{if(done)return;done=true;pc.removeEventListener('icegatheringstatechange',check);resolve();};const check=()=>{if(pc.iceGatheringState==='complete')finish();};pc.addEventListener('icegatheringstatechange',check);setTimeout(finish,timeout);});
  D.newPeerConnection = () => new RTCPeerConnection({iceServers:D.ICE_SERVERS});
  D.gameDoc = () => { try { return D.frame.contentDocument; } catch { return null; } };
  D.hideGameMenu = () => D.gameDoc()?.getElementById('main-menu')?.classList.add('hidden');
  D.showGameMenu = () => { try { D.mp.game?.showMainMenu?.(); } catch {} };
  D.escapeHtml = (value) => String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  D.peerForSeat = (seat) => { for(const p of D.mp.peers.values()) if(p.seat===seat&&p.connected)return p; return null; };
})();
